### ISSUE TITLE
提一个简历

### ISSUE THREAD

**Issue by lincol29** [oxyry/qireader#105]
作者能否出一个IOS版本的APP呢，一般使用还是在手机上居多。相当于看新闻一样的啦

**Comment by weijarz** [comment]
QiReader已经适配了PWA WebApp规范。
在iOS上只要用Safari打开网站，然后点击底下工具栏中间的分享按钮，再点“添加到主屏幕”，就会象原生App一样安装到主屏幕，从主屏幕图标打开时会表现得象原生App（没有浏览器的工具栏/可以独立出现在任务列表等）。
