### ISSUE TITLE
Ipv6 访问

### ISSUE THREAD

**Issue by xiaorong61** [oxyry/qireader#106]
建议开启 Ipv6 的访问支持，因为有些 vps 的 ipv6 线路比 ipv4 更好。

**Comment by weijarz** [comment]
听说有些地区的ipv6不稳定，我也不是很确定，我会先开个专用域名试试，比如 `6.qireader.com` 之类。

我这边对外提供服务的节点是国内优化线路，基本不会丢包和卡，即使有 ipv6 应该也不会更快。

**Comment by xiaorong61** [comment]
哈哈我没表述清楚，我说的 vps 是用户用来翻墙的 vps
