### ISSUE TITLE
QiReader无法及时推送小红书文章

### ISSUE THREAD

**Issue by JerryYang-30** [oxyry/qireader#109]
我用的RSSWorker来生成RSS订阅源：https://github.com/yllhwa/RSSWorker
图1为小红书订阅源，图2为Bilibili订阅源。可以看见，小红书订阅源爬取的XML没有笔记的发布日期pubDate，这导致订阅小红书源时，没有按照顺序推送历史笔记。如图3，笔记时间全都是5月10日，与实际不符。
另外，小红书笔记的更新也无法及时在QiReader里推送（在Inoreader及时推送了）。如图3，只推送到6月3日，但在小红书可以看到作者于6月3日之后实际更新了9篇笔记。看此前的Issues，貌似跟小红书置顶文章有关？但我不懂编程，不知道怎么修改RSS生成规则😭
小红书原地址：https://www.xiaohongshu.com/user/profile/587212eb50c4b476ef6142a7
小红书RSS源：https://rss-worker.jerry30yang.workers.dev/rss/xiaohongshu/user/587212eb50c4b476ef6142a7
Bilibili原个人空间：https://space.bilibili.com/1405395281
Bilibili的RSS源（有时可能失效，疑似跟爬取频率有关。这个是RSSWorker的问题）：https://rss-worker.jerry30yang.workers.dev/rss/bilibili/user/dynamic/1405395281
![image](https://github.com/oxyry/qireader/assets/102589310/ede169c6-b340-4bd8-a0cd-e0a9a2c7b5ad)
![RSS爬取的B站XML格式](https://github.com/oxyry/qireader/assets/102589310/6fa43729-557d-40ff-bd6c-91266d4cd111)
![image](https://github.com/oxyry/qireader/assets/102589310/71830abb-9b57-48d7-be2c-f4df4925b26f)

**Comment by weijarz** [comment]
确实，因为之前这边预设源里的文章是按时间顺序排的。这几天内会修复这个问题。

**Comment by JerryYang-30** [comment]
> 确实，因为之前这边预设源里的文章是按时间顺序排的。这几天内会修复这个问题。

好，感谢作者。修复好了可以dd我一下吗哈哈

**Comment by weijarz** [comment]
@JerryYang-30 今天的更新应该已经修复了这个问题。

**Comment by JerryYang-30** [comment]
> @JerryYang-30 今天的更新应该已经修复了这个问题。

好，已经可以看到最新笔记了，感谢作者🥰
