### ISSUE TITLE
推特部分订阅源无法订阅

### ISSUE THREAD

**Issue by ioypl** [oxyry/qireader#110]
Inoreader可以全部订阅，但是部分推特账户却无法订阅。

**Comment by ioypl** [comment]
非常完美的RSS阅读器，就是推特无法全部订阅，这点非常痛，导致我现在也没有订阅高级套餐。

**Comment by ioypl** [comment]
> 具体的RSS地址是什么？ Twitter不能直接订阅，需要通过 rsshub 之类的网站转一下，比如 https://rsshub.app/twitter/user/DIYgod

ttps://rsshub.app/twitter/user/435h，是通过rsshub订阅的，一部分可以，一部分不可以，很奇怪，但是Inoreader又全部可以

**Comment by weijarz** [comment]
@ioypl 你这个地址在浏览器里就是打不开的。 inoreader应该是以前可以打开的时候有人添加了，然后存在旧数据，但已经不更新。

**Comment by ioypl** [comment]
> @ioypl 你这个地址在浏览器里就是打不开的。 inoreader应该是以前可以打开的时候有人添加了，然后存在旧数据，但已经不更新。

我试了除inereader外的其他主流RSS阅读器，都能订阅，而且是时刻更新的，都能收到更新。我非常喜欢你这一款阅读器，但是就是这个解决不了，是心头痛。

**Comment by weijarz** [comment]
这个不是我这边的问题。因为这个订阅源用任何工具如浏览器打开就是429 Too Many Requests错误。可能是偶尔可以打开，但在添加的时候不能打开，所以添加不了。
别的热门阅读器可以是因为用的人多，以前这个源服务稳定的时候被人添加过了，只要添加上了，因为会定时更新且偶尔一次可以更新成功，所以表现得能收到更新。

**Comment by ioypl** [comment]
> 这个不是我这边的问题。因为这个订阅源用任何工具，如浏览器打开就是429 Too Many Requests错误。可能是偶尔可以打开，但在添加的时候不能打开，所以添加不了。 别的热门阅读器可以是因为用的人多，以前这个源服务稳定的时候被人添加过了，只要添加上了，因为会定时更新且偶尔一次可以更新成功，所以表现得能收到更新。

明白，功能建议，能否加入win11通知和订阅源列表手动排序功能。
