### ISSUE TITLE
建议显示已有订阅源数量

### ISSUE THREAD

**Issue by JerryYang-30** [oxyry/qireader#113]
因为订阅源数量是有上限的，所以想知道自己目前已经订阅了多少。
目前只能先导出opml文件，然后在文件里Ctrl + F搜索 xmlUrl 才知道订阅了多少，显得麻烦了

**Comment by JerryYang-30** [comment]
今天的更新好像已经完成此功能了，我也是偶然才发现😂希望作者之后可以添加一下更新日志

**Comment by weijarz** [comment]
更新日志已经添加。 
https://github.com/oxyry/qireader/blob/main/CHANGELOG.md
