### ISSUE TITLE
是否考虑开发客户端呢？

### ISSUE THREAD

**Issue by JokeenZhang** [oxyry/qireader#117]
日常使用是足够了，但是过于依赖浏览器了，一些阅读数据，收藏等，希望能有自己的缓存，或者保存到本地

**Comment by weijarz** [comment]
这边应该不会推出原生客户端，开发成本太大了。

数据的导出功能会在后续添加。也可能允许定期增量备份数据到一些外部存储空间。

**Comment by JokeenZhang** [comment]
我家多个电脑，数据不同步也挺烦人，每次手动保存数据还是繁琐了点

**Comment by weijarz** [comment]
我没理解你说的。
这边数据（订阅和收藏之类）只要登录的是同一个账号不同设备上是同步的。

**Comment by JokeenZhang** [comment]
包括RSS上的文章都是同步的吗？比如我有一台老电脑很久没有使用，打开后也能有相同数量的RSS文章吗？

**Comment by weijarz** [comment]
是的。因为数据是放在服务器端的，本地只有少量缓存，只要刷新一下网页就同步了。
