### ISSUE TITLE
打开文章列表标题的超链接后，是否可以自动把该文章标记为已读

### ISSUE THREAD

**Issue by JerryYang-30** [oxyry/qireader#118]
用浏览器内置点击方式，比如 `ctrl/shift + 鼠标左键` 或 `鼠标中键` 点击文章列表标题的超链接之后，能否自动把该文章标记为已读？（鼠标手势点击先不考虑了，可能太麻烦）

**Comment by weijarz** [comment]
现在可以了。

不过中键和手势不行。ctrl/shift + 左键可以。
