### ISSUE TITLE
Error: Not a feed document

### ISSUE THREAD

**Issue by shenweiyan** [oxyry/qireader#119]
超能网的订阅：https://www.expreview.com/rss.php

发现失效无法订阅了，一直提示 "**此订阅源有问题。请检查并在必要时重新订阅。Error: Not a feed document**"，删除后重新订阅还是同样的问题。

![Clip_2024-09-09_16-03-26](https://github.com/user-attachments/assets/bef823f5-6d0b-4326-bbdd-2b7ac4ad9b6d)

**Comment by weijarz** [comment]
这是因为超能网错误地配置了他们的服务器，对这个RSS地址进行了反爬设置，导致所有阅读器都取不到他家的RSS,比如Inoreader之类的阅读器也取不到。
只能向超能网反映这个问题。
