### ISSUE TITLE
发现有订阅源单独访问能够显示，但在“全部”及自定义文件夹页面中无法显示出来

### ISSUE THREAD

**Issue by MicrowaveOven1** [oxyry/qireader#121]
![image](https://github.com/user-attachments/assets/38488c1a-9c60-4d81-8b9e-6f38d7d0fa20)
![image](https://github.com/user-attachments/assets/01ac5e82-39eb-47a2-8556-48694d1ec927)
整体设计利落优雅，但这个问题很是困惑，出现问题的订阅源地址：https://rsshw.win/asus/bios/rog-strix-b760-g-gaming-wifi?limit=1

**Comment by weijarz** [comment]
目前的实现细节是这样的：
- 一个月前的未读文章会被自动标为已读（类似feedly和inoreader都这样）。
- 文件夹中的文章只保留一个月的（【全部】也是个文件夹）。
- 对于默认的“只显示未读”设定来说文件夹只保留一个月没什么问题，因为一个月前的文章会被自动标为已读不会出现在列表中。但如果要看某个源一个月前的已读文章，就只能打开这个单独的源了。

**Comment by MicrowaveOven1** [comment]
谢谢 这下搞明白了，还以为是配置上出了奇怪的问题
