### ISSUE TITLE
希望订阅源可以手动排序

### ISSUE THREAD

**Issue by luo-chuan** [oxyry/qireader#123]
如题。注意不是文章排序，是订阅源排序。
订阅源一多，找起来就麻烦。希望可以手动排序，这样就可以把自己最喜欢的订阅源排在前面。

**Comment by weijarz** [comment]
这个功能在计划中，预计很快会上线。

**Comment by luo-chuan** [comment]
不要置顶功能，到时候置顶的一多，又乱套了。直接就是完全手动排序。

**Comment by weijarz** [comment]
置顶比较好操作和实现，类似微信那种。而且我觉得对大部分人来说并没有精确排序大量源的需求，只有少量的文件夹需要置顶。

**Comment by weijarz** [comment]
已经在订阅源上下文菜单中添加了置顶功能。
