### ISSUE TITLE
与竞品PoweReader的比较

### ISSUE THREAD

**Issue by luo-chuan** [oxyry/qireader#124]
https://powereader.app/zh/guide/
PoweReader提供了ios和mac os的客户端，实现了沉浸式翻译、全文获取、离线阅读的功能。
而Qi Reader目前只提供了网页端，对安卓和windows用户很友好，但因为没有客户端，所以无法离线阅读。另外缺少沉浸式翻译功能，需借助浏览器插件immersive translate来实现双语阅读。
做成APP对于开发者来说也有好处，就是可以获得更多的用户。如果要做客户端的话，希望一步到位，直接用跨端框架，支持win+mac+linux+android+ios。

**Comment by weijarz** [comment]
我比较喜欢Web端的阅读体验，点开链接等也都在浏览器里，收藏书签之类的都很方便。如果以Web为基础做跨端的话，那和添加网站到主屏幕的体验也差不了多少。如果额外用别的技术做跨端的话，维护二套代码成本过大了。离线阅读之类的功能，Web端要做也是能做的。

而且App端自由度小，能不能上架或以后会不会下架还不好说，毕竟这边是可以直接添加境外源的，和本地的阅读器不一样。

**Comment by luo-chuan** [comment]
> 而且App端自由度小，能不能上架或以后会不会下架还不好说，毕竟这边是可以直接添加境外源的，和本地的阅读器不一样。

如果要规避这个风险，就只能发布到play商店或app store美区，但这样一来，受众就小了，开发成本远大于收入，还是算了。我用qi reader就是来看英语新闻的，不能添加境外源的话，反而我不大愿意用了。
