### ISSUE TITLE
内嵌网页视图 大量循环请求 且显示空白

### ISSUE THREAD

**Issue by shiluanzzz** [oxyry/qireader#131]
我这边所有的订阅源 在使用 “内嵌网页视图” 查看内容的时候 都是空白
<img width="2047" alt="image" src="https://github.com/user-attachments/assets/126a6e0e-8fd1-42c4-be6a-21554189c38b">
通过 F12 查看请求，在点击之后，开始发送大量重复的请求

参考订阅源：
https://www.zhihu.com/rss

**Comment by weijarz** [comment]
确实有问题。这二天内会修复。

**Comment by weijarz** [comment]
已经修复了。

很多网站使用http头标记不能被别的网站用iframe嵌入，也有网站检测到被嵌入时只显示警告信息，比如知乎似乎就不能被嵌入。一般大站会加上这个安全选项，个人博客之类一般不会。

所以，对这种网站最好用新页面打开。在文章列表设置上可以选上“在新页面打开”。
在订阅源设置这里，后续也会加入一个在新页面打开的选择项。

**Comment by weijarz** [comment]
另外iframe嵌入还有一个坏处，手势功能不能在iframe上使用，无法用手势返回列表或转到下一个文章。也不能用键盘滚动页面，所以之前考虑过取消这个功能。

**Comment by shiluanzzz** [comment]
@weijarz 已经更新上线了吗？ 
刷新页面后显示最后构建: 2024/10/12 11:32:01
<img width="2030" alt="image" src="https://github.com/user-attachments/assets/f00ef817-2d34-4d90-80bf-b2932cf2b02c">
其次微信公众号订阅的页面也无法使用嵌入页面打开，正文抓取功能也无法抓取到正常内容。
<img width="2040" alt="image" src="https://github.com/user-attachments/assets/d5023edb-e335-4283-a882-dadbcaeb6a94">

**Comment by weijarz** [comment]
是的。你看这些网站就不能被嵌入。

**Comment by shiluanzzz** [comment]
那就蛮可惜了, fluent reader 好像是没有这种限制问题

**Comment by weijarz** [comment]
因为那个是本地软件，可以绕过这个安全限制。
这边的话，如果浏览器可以安装插件，也可以装个修改http header的插件绕过这个问题，只要匹配目标域名去掉http回应里的 X-Frame-Options 和 Content-Security-Policy 这二个http头就行了。
