### ISSUE TITLE
需求：用户自定义css片段

### ISSUE THREAD

**Issue by luo-chuan** [oxyry/qireader#133]
rss订阅源千奇百怪，很难统一适配好。针对某个rss，应允许用户自定义css片段，来消除一些排版问题。
比如此[issue](https://github.com/oxyry/qireader/issues/127)提到的svg过大的问题。
又比如此订阅源（`https://plink.anyfeeder.com/bbc/technology`）中显示多余的白色图片问题。
![图片](https://github.com/user-attachments/assets/4178f2cf-abb6-4d27-90a5-2ca38008e91e)
Q：为什么一定要通过qireader来设置css，而不是通过浏览器插件呢？
A：因为用户有时会查看原网页，通过qireader来设置css就不会对原网页造成影响。

**Comment by luo-chuan** [comment]
不过好像可以通过浏览器插件，限制css片段只对qireader生效。大佬可以再评估一下。

**Comment by weijarz** [comment]
一般输出全文的源不会有这种问题,转全文的时候因为全文算法的原因可能会带上些不需要的空白图片。这个bbc应该已经是全文了不需要再转全文。
svg过大这类的可以通过一些算法解决，之前svg过大的问题现在应该已经不会了，这边限制了行内图片元素的大小。

**Comment by luo-chuan** [comment]
> 一般输出全文的源不会有这种问题,转全文的时候因为全文算法的原因可能会带上些不需要的空白图片。这个bbc应该已经是全文了不需要再转全文。

如果暂时不做用户自定义css，麻烦把这个图片 `https://www.bbc.com/bbcx/grey-placeholder.png` 屏蔽一下吧，就是截图中的白块，深色模式下看着挺难受的。

**Comment by weijarz** [comment]
自定义CSS这几天会开始实现，不出意外的话1-2星期会上线。
想想CSS方案还是最灵活可玩性高，比如还能引入外部字体之类。

**Comment by weijarz** [comment]
已经在「设置/文章内容」页面新增了“自定义 CSS”设置项。

----- 

- 这些自定义CSS内容会放在文章内容选择器下，比如
```css
.article-text {
  /* 用户 CSS 代码会插入在这里 */
}
```

所以可以直接写 CSS 样式，比如 `font-family: xxx;`，不需要写选择器。

----- 

- 如果需要选择正文里面的特定内容，比如禁用图片 `img { display: none }`，需要浏览器支持 CSS Nesting， Chrome >= 120, Safari >= 17.2, Firefox >= 117

----- 

- 如果要为特定网站的文章定制 CSS,可以用 CSS Nesting 的写法实现，比果这贴里的隐藏来自 BBC 的空白图片：
```css
&[data-article-url*="bbc.com"] {
  img[src*="placeholder"] { display: none; }
}
```

**Comment by luo-chuan** [comment]
测试没问题。我关闭issue了。
