### ISSUE TITLE
RSS Feed does not display images properly. And thumbnails of many articles are missing

### ISSUE THREAD

**Issue by FridayKnight4** [oxyry/qireader#134]
I love your reader ! Two problems:
1.The following RSS URL usually displays full text + picture in Feedly, Inoreader etc: https://www.bta.bg/bg/rss/free
But not here. The feed is imageless. Can you please check and try to fix it?
2. Many RSS URLs lack thumbnails:
![image](https://github.com/user-attachments/assets/0a2fb10d-0e8a-4b84-a31a-0be9598acd0b)
![Screenshot](https://github.com/user-attachments/assets/86bc5f19-7898-4eb7-b194-3d60b37f02ef)

You fixing these problems would make me very happy and make me leave Inoreader and even try your monthly subscriptions.

Thank you very much in advance

**Comment by weijarz** [comment]
Issues related to these sources have been fixed. New entries will load images correctly.
