### ISSUE TITLE
Embed Tweets if the article contains some!

### ISSUE THREAD

**Issue by FridayKnight4** [oxyry/qireader#137]
First of all, thank you for this wonderful product!
Everything is great so far, only one more issue. Please see the screenshots. Same article, displayed on Qireader and Inoreader. Can you please embed tweets the way they do? In this way ww users will no longer have to exit feed view in order to see a tweet. Thank you so much in adcance for you effort and your time, even if your response will be „no“❤️
![IMG_6747](https://github.com/user-attachments/assets/86344298-4095-4a80-b249-2f1e711f3ff1)
![IMG_6746](https://github.com/user-attachments/assets/62d82ba2-2a8a-4918-ae93-959592dbd756)

**Comment by weijarz** [comment]
For X/Twitter feeds, you can now embed Tweets by selecting "Inline WebPage" in the "Default View" option in "Subscription Properties" page.
