### ISSUE TITLE
希望可以去掉标题中的 HTML 标记

### ISSUE THREAD

**Issue by PaulHerrero** [oxyry/qireader#14]
![image](https://user-images.githubusercontent.com/56058332/200212451-643c3de6-c723-4bc4-887a-bedee302904a.png)

如图，标题中会显示 HTML 标记，希望可以去掉。感谢

**Comment by weijarz** [comment]
@PaulHerrero 第一次看到标题里会出现 HTML 标记。RSS 标准里的标题应该只允许纯文本。如果直接去掉的话正常标题里有<xxx>的内容就会出问题了。

**Comment by PaulHerrero** [comment]
> @PaulHerrero 第一次看到标题里会出现 HTML 标记。RSS 标准里的标题应该只允许纯文本。如果直接去掉的话正常标题里有的内容就会出问题了。

这样啊，好吧。这个 rss 我是通过 Google alert 生成的，会在监测到关键词后发布到rss里，可能因为这个会有加粗标记吧

**Comment by weijarz** [comment]
今天更新了源内标题上的html相关逻辑，按标准明确指定标题是html格式的情况下会正确去掉html标记。
