### ISSUE TITLE
Feed does not display pictures

### ISSUE THREAD

**Issue by FridayKnight4** [oxyry/qireader#141]
Dear Team,

First, thank you for this lovely product and for the good support in several occasions! You really made me leave Inoreader after 3 years for your RSS reader.

I have a small issue. My favorite feed does not display pictures when on Webpage Text:

https://www.dailymail.co.uk/sport/football/index.rss

Can you please take a look if you have the time? I‘d lobe to habe the images embedded together with the text.
Thank you very much in advance.

**Comment by weijarz** [comment]
Thank you so much for your support.
This feed has been fixed. 
(Older posts may not be displaying images properly yet because of caching.)
