### ISSUE TITLE
快捷键O的功能改进

### ISSUE THREAD

**Issue by ttttmr** [oxyry/qireader#144]
个人的使用模式

1. 在文章列表中使用`J` `K`导航，找到想看的文章
2. 按下`O`看全文，使用`J` `K`滚动浏览
3. 看完了，希望回到文章列表，此时需要按`H`才能回到文章列表，继续第一步的动作

`O`的功能可以改为打开或关闭文章

在第三步中，就可以再次按`O`回到文章列表，全程只需三个按键

以上是在多列视图的表现，在杂志视图中

`O`打开文章后，目前没有快捷键能够关闭文章，从而回到文章列表页面

如果再次按`O`，关闭文章，回到文章列表，使用起来会更加方便

**Comment by weijarz** [comment]
在杂志视图中打开文章后也是按 H 回到列表，和多列是一样的。
当然再次按 O 关闭看上去也很不错，应该会在后面加上。

**Comment by weijarz** [comment]
已解决。
