### ISSUE TITLE
订阅失败HTTP Error 400: Error: Destination HTTP error 403

### ISSUE THREAD

**Issue by ttttmr** [oxyry/qireader#146]
RSS地址 https://www.thousandeyes.com/blog/feed/

提示

> 加载网页失败。
> HTTP Error 400: Error: Destination HTTP error 403

**Comment by weijarz** [comment]
查了下是因为这个源必须要用 gzip 传输编码，而这边最近改了http库暂时还没加个这个支持。
会在几天内修复。

**Comment by luo-chuan** [comment]
这个源也订阅不了，但在follow里就能订阅。
`https://www.rfa.org/arc/outboundfeeds/english/rss/`
![Screenshot_20241123_171912_com_lemurbrowser_exts_WebappActivity](https://github.com/user-attachments/assets/223f742a-e9bb-443c-bbd3-006eda05dd20)

**Comment by weijarz** [comment]
这二个源已经修复。
