### ISSUE TITLE
Atom RSS订阅失败

### ISSUE THREAD

**Issue by ttttmr** [oxyry/qireader#147]
RSS地址 https://govuln.com/news/feed/

提示

> 这个网址不包含 RSS 订阅源。

可能是content-type没支持application/atom+xml？

**Comment by weijarz** [comment]
最近更改了http底层库和相关代码，这里的逻辑处理有点问题。
比如这个URL后面有个"/"，这边请求的时候是不带"/"，一般也没什么问题，但这个Feed特殊，不带"/"会返回一个 200 码，但内容不是Feed而是个404错误页面。
这几天会修复。

**Comment by luo-chuan** [comment]
这个源也订阅不了，但在follow里就能订阅。
`https://www.rfa.org/arc/outboundfeeds/english/rss/`

**Comment by weijarz** [comment]
已经修复。
