### ISSUE TITLE
订阅失败HTTP Error 400: Error: Fetch error: Error: read ECONNRESET

### ISSUE THREAD

**Issue by ttttmr** [oxyry/qireader#148]
RSS https://wooyaa.me/feed/

提示

> 加载网页失败。
> HTTP Error 400: Error: Fetch error: Error: read ECONNRESET

**Comment by weijarz** [comment]
这个RSS确实本身有问题，没办法加载，哪怕我用curl完全模仿浏览器的请求方式也不行，别的阅读器现在应该也是加载不了的。
