### ISSUE TITLE
全文加载乱码

### ISSUE THREAD

**Issue by ttttmr** [oxyry/qireader#149]
RSS https://rsshub.xlab.app/rsshub/transform/html/https%3A%2F%2Fwww.dapenti.com%2Fblog%2Fblog.asp%3Fsubjectid%3D70%26name%3Dxilei/item%3Dli%26encoding%3Dgb2312?code=7e8c29883989ab2937dc7bd22bb5cd4f

网页是GB2312的

**Comment by weijarz** [comment]
感谢反馈，已经修复。
之前的文章会有缓存，所以可能还会乱码。
