### ISSUE TITLE
My feed has updated, but QiReader does not

### ISSUE THREAD

**Issue by bumpkin00** [oxyry/qireader#153]
why does this happen?

My feed is https://rsseverything.com/zh/feed/67fe40d9-d200-40eb-b9f5-373f37619aa1.xml

My feed leads to the new content which is created today, but on QiReader it is still the old content of yesterday

**Comment by weijarz** [comment]
不是源一有更新这边立刻会同步更新，会有半小时至一小时左右的延迟。
