### ISSUE TITLE
部分rsshub.app订阅源报错

### ISSUE THREAD

**Issue by luo-chuan** [oxyry/qireader#154]
链接：`https://feedx.run/rss/chinadaily.xml`
当前日期：2024-12-01

![图片](https://github.com/user-attachments/assets/25780f13-f204-49cb-a36f-50a80b004d11)

用follow测试没问题

![图片](https://github.com/user-attachments/assets/0fd0b090-7388-44a5-aa07-186f1fc17249)

**Comment by luo-chuan** [comment]
同样的问题还有这个非官方美联社的源，它们都是同一网站出品：
`https://feedx.run/rss/ap.xml`

**Comment by luo-chuan** [comment]
还有这个非官方雅虎新闻，我就不单独开issue了：
`https://rsshub.app/yahoo/news/en/world`
![图片](https://github.com/user-attachments/assets/24df2c27-1e25-4a45-9271-8c039b9e4dc7)

**Comment by weijarz** [comment]
有订阅源问题可以先用浏览器打开这个源地址试，浏览器都打不开的话阅读器当然也是打不开的。
我用浏览器打开 https://feedx.run/rss/chinadaily.xml 都显示域名过期了，别的阅读器也不可能正常。

**Comment by luo-chuan** [comment]
确实`feedx.run`这个域名过期了，换成`feedx.net`就好了。

但`rsshub.app`的这几个源还是刷新不出内容并且报错，麻烦再看看呢。比如：
`https://rsshub.app/abc`
`https://rsshub.app/cnbc/rss`

**Comment by luo-chuan** [comment]
> https://rsshub.app/abc 这个在浏览器里就打不开。 https://rsshub.app/cnbc/rss 用浏览器第一次打开有cf的人机验证，这种也是不行的，因为这边的爬虫不会过人机验证。

好的，那我就关闭了。
