### ISSUE TITLE
发送至kindle的中文内容电子书默认显示字体是英文字体

### ISSUE THREAD

**Issue by KelseyShi** [oxyry/qireader#158]
发送至kindle的中文内容电子书默认显示字体是英文字体，导致中文字体显示粗细不均，阅读起来困难。

设置页-电子书和kindle-文件选项里已经设置语言为简体中文。
机型：kindle scribe

**Comment by weijarz** [comment]
谢谢反馈，已经修复了。
在qireader推送设置里语言也要选择中文，否则还是默认英语。
