### ISSUE TITLE
在杂志视图中希望有选项直接访问原文

### ISSUE THREAD

**Issue by yi-Xu-0100** [oxyry/qireader#16]
有的时候不倾向于在阅读器里看，想访问原文，但是还是需要点击进入条目后再点击标题，有点繁琐。

希望能够通过杂志视图，在卡片的右边增加按钮方便直接访问原文，或者分享什么的~

![image](https://user-images.githubusercontent.com/25523606/202832234-9c6e27ca-2d5c-48b1-b78c-90e8af5ce119.png)

**Comment by weijarz** [comment]
这个计划会在列表项上添加悬浮菜单/右键菜单来实现这些功能。
目前可以用键盘定位到相应条目后按 V 键直接打开源网页，用鼠标的话按 Shift + 单击也行。
