### ISSUE TITLE
内嵌网页浏览显示拒绝连接

### ISSUE THREAD

**Issue by analogyworld** [oxyry/qireader#21]
感谢作者，这个rss浏览器有内嵌网页的功能，很好满足了我现在的需求。
但有个问题是，我发现部分订阅源使用内嵌网页时，显示拒绝连接。如下面的图。
实例的订阅源为 https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=sciadv
![image](https://user-images.githubusercontent.com/122202105/211991644-5d795733-cf8a-4efa-a226-ea2f45fc14a9.png)

**Comment by weijarz** [comment]
@analogyworld 有些网站出于安全原因使用 http 头 x-frame-options 阻止被第三方网页嵌入，这些网站就不能用这个视图，只能在新网页打开。
