### ISSUE TITLE
优化建议: 设置行宽

### ISSUE THREAD

**Issue by yangS97** [oxyry/qireader#27]
目前手机上浏览没有什么问题,
但是电脑上浏览时,左右两侧的空余太大了, 阅读观感不好, 
建议调宽一个, 或者提供一个设置选项, 可以调整

**Comment by yangS97** [comment]
> 在桌面端已经加上了这个设置。

没找到, 是这个吗?  
![image](https://user-images.githubusercontent.com/50876778/226917983-be173ec8-9f2d-40d4-a728-ae54daa8e1db.png)

**Comment by weijarz** [comment]
@yangS97 视图选项这个。如果里面没有“文本宽度”就刷新下页面。如果刷新不行就关闭浏览器再开。

**Comment by yangS97** [comment]
可以了, 感谢
