### ISSUE TITLE
建议箭头指示的地方建议上下滑动的时候隐藏。

### ISSUE THREAD

**Issue by jacknnnbauer** [oxyry/qireader#28]
如图所示，箭头指示的地方建议上下滑动的时候隐藏。

![InkedScreenshot 2023-03-28 054009](https://user-images.githubusercontent.com/19789020/228122074-f1cf1a42-65c1-4ab4-a623-b510ceafa311.jpg)

**Comment by lakerlao** [comment]
严重同意，上面部分比较占用视觉空间

**Comment by weijarz** [comment]
已修复。在移动设备上自动启用，在PC上可以在设置中开启。
