### ISSUE TITLE
关于IOS浅色背景滑动条会看不见的问题

### ISSUE THREAD

**Issue by Jagger-li** [oxyry/qireader#31]
如题，很多时候滑动条会「看不见」，只有遇到图片时才会露出来，希望能优化

**Comment by weijarz** [comment]
@Jagger-li 这是号称新时代IE的Safari的成吨Bug的其中一个😄
参见 https://bugs.webkit.org/show_bug.cgi?id=216140

绕过的办法也是有的，不过稍麻烦。最近几月苹果礼貌性地稍稍加快了一丢丢Safari的开发进度，再等等看希望苹果修了这个。

**Comment by Jagger-li** [comment]
感谢回复，了解了

**Comment by weijarz** [comment]
@Jagger-li 这问题应该只出现在深色系统下选浅色主题或反之。选“自动”来根随系统主题应该不是会这个问题。

**Comment by Jagger-li** [comment]
确实是，我就说怪不得晚上才看不到滑动条。不过我喜欢浅色主题阅读，算了😂



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weijarz ***@***.***&gt;
发送时间: 2023年4月20日 20:47
收件人: oxyry/qireader ***@***.***&gt;
抄送: Jagger-li ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[oxyry/qireader] 关于IOS浅色背景滑动条会看不见的问题 (Issue #31)





 
@Jagger-li 这问题应该只出现在深色系统下选浅色主题或反之。选“自动”来根随系统主题应该不是会这个问题。
