### ISSUE TITLE
若订阅源分组的名称包含”/“会出现异常

### ISSUE THREAD

**Issue by lyizhuo** [oxyry/qireader#32]
![屏幕截图 2023-04-21 223249](https://user-images.githubusercontent.com/64514694/233664716-7198cb82-667e-4f01-9d36-3e2feae33358.png)
如图，当订阅源分组的名称中包含`/`，会显示”页面未找到“，也无法删除该分组，希望开发者能修复😂

**Comment by weijarz** [comment]
@lyizhuo 谢谢反馈，已解决。
