### ISSUE TITLE
PubMed网站feed无法识别

### ISSUE THREAD

**Issue by tang-colorful** [oxyry/qireader#35]
PubMed网站生成的RSS链接无法识别 https://pubmed.ncbi.nlm.nih.gov/rss/search/1pKPPKMR3L28s871PA1OdUqNqbsd3HVd8nrbzobwucwgFHZs5m/?limit=15&utm_campaign=pubmed-2&fc=20230510074044

**Comment by weijarz** [comment]
@tang-colorful 已经修复了。
