### ISSUE TITLE
无法拉取新信息了，服务器崩了么？

### ISSUE THREAD

**Issue by LZD121** [oxyry/qireader#36]

**Comment by weijarz** [comment]
我这边没问题啊？你用的是 qireader.com 域名还是 qireader.com.cn 域名？

**Comment by LZD121** [comment]
用了qireader.com.cn可以了，谢谢。
qireader.com好像不行了。

________________________________
发件人: weijarz ***@***.***>
发送时间: 2023年5月18日 10:46
收件人: oxyry/qireader ***@***.***>
抄送: LZD121 ***@***.***>; Author ***@***.***>
主题: Re: [oxyry/qireader] 无法拉取新信息了，服务器崩了么？ (Issue #36)


我这边没问题啊？你用的是 qireader.com 域名还是 qireader.com.cn 域名？

―

**Comment by weijarz** [comment]
经这段时间反馈国内有少量地区到特定服务器线路不通（这边的服务器都位于境外）。
这边有三个不同的网站代理节点，按从上到下优先顺序使用即可，都不通的可能性就不大了。
www.qireader.com.cn
www2.qireader.com.cn
www.qireader.com
