### ISSUE TITLE
批判一番悄悄减少免费套餐订阅数的操作

### ISSUE THREAD

**Issue by nbqrg** [oxyry/qireader#38]
如题。

你们搞的这个东西啊，excited。

但是呢，有一点不好。之前在更新记录里写了，免费套餐的订阅量提升到 50 个。结果我今天发现，又减到 30 个了。

而这一点，就没在更新记录里体现。

这好么？这不好。

虽然我当时就订阅了一个五年的 PRO 套餐，很快啊！

但是啊，你们这样是不行得，I am angry！

我今天算是得罪了你们一下！希望你们好自为之！

**Comment by weijarz** [comment]
谢谢订阅支持！
😄因为算不上是功能变化，同时也忘写了相比之前大幅降低了付费费用，以后这类运营方面变化也会加上。
