### ISSUE TITLE
请提供批量管理订阅源分组的功能

### ISSUE THREAD

**Issue by nbqrg** [oxyry/qireader#39]
RT，现在分组需要到每个订阅源里去设置，太麻烦了。

**Comment by weijarz** [comment]
批量处理暂时这个功能难以实现，需要服务器这边做一个大的优化。等完成后会考虑加上。

**Comment by JunQu** [comment]
@weijarz 
能否支持拖拽分组

**Comment by weijarz** [comment]
@JunQu 计划会添加这个功能。
当前是按数字字母顺序排列，如需放到前面可以在名字前面加个数字序号。

**Comment by JamYiz** [comment]
拖拽排序和分组，还有订阅源右键设置能加上吗，会方便很多

**Comment by weijarz** [comment]
已经在订阅源上下文菜单中添加了置顶功能。
