### ISSUE TITLE
滑动选择文本时与左右滑易冲突

### ISSUE THREAD

**Issue by Mdreame** [oxyry/qireader#41]
## 问题
当滑动选择文本时，会触发左右滑动选项。**立即放手**会返回或跳转下一条。

![image](https://github.com/oxyry/qireader/assets/21331592/472e3524-ed50-4966-8872-8661db5730c4)

现在是可以保持选中状态，**等两秒钟**左右，待左右滑动选项取消后再抬起鼠标（手指）。

## 解决？
能否切换选中方式呢？比如：
- 双击选中句子
- 三击选中段落

**Comment by weijarz** [comment]
打算用有选区时禁用滑动手势的方式解决。
这样完全不会影响正常的选择操作，后续需要滑动手势只要点击一下其它文字取消选择即可。

**Comment by Mdreame** [comment]
iphone上完美解决了，edge、chrome上好像还有问题。不过主要用手机，可以了。

**Comment by weijarz** [comment]
@Mdreame 你说的edge/chrome是什么平台上的？这边对非触摸屏是禁用文章页的滑动手势的按理在pc上不会有这个问题。

**Comment by Mdreame** [comment]
> @Mdreame 你说的edge/chrome是什么平台上的？这边对非触摸屏是禁用文章页的滑动手势的按理在pc上不会有这个问题。

已解决
---
**设备**：huawei matebook14 带触摸屏。

**我做了什么**

1. 我清空浏览器缓存并刷新后，问题还是存在，如下图：
![image](https://s31.aconvert.com/convert/p3r68-cdx67/r1a50-2j5qn.gif)
2. 关闭触摸屏功能，再尝试，问题依旧。
3. 开启新窗口而非新标签页登录，这次没有问题。

以上都是在edge上操作的。chrome刷新后就正常了。原因可能还是缓存没清除干净吗？我不太懂。

thanks anyway 🌻

**Comment by weijarz** [comment]
那有可能是缓存的问题。因为用了PWA技术后常规刷新操作有时不管用，后继再次打开这个网页才会更新页面（比如关了tab或重启浏览器）。
