### ISSUE TITLE
请问https://navi.cnki.net/knavi/rss/DLXB显示“这个网址不包含 RSS 订阅源”是什么原因？

### ISSUE THREAD

**Issue by shichunjiegit** [oxyry/qireader#46]
https://navi.cnki.net/knavi/rss/DLXB
提示：这个网址不包含 RSS 订阅源。

**Comment by weijarz** [comment]
@shichunjiegit 这个页面对国外IP做了特殊处理，用国外的IP抓取会直接跳到主页。
