### ISSUE TITLE
赞赏码的付费方式有限制

### ISSUE THREAD

**Issue by JunQu** [oxyry/qireader#49]
如果使用赞赏码付款，限制字数在16位，如果邮箱尾部 @xxx.com 就占了 7-9 位，而现在较短邮箱名已被占用完了，超过七位的用户名也不算少见，这样就会无法留言完整邮箱了

**Comment by JunQu** [comment]
荔枝的还要登录等等，看着还挺麻烦的

**Comment by weijarz** [comment]
邮箱尾部没输入完整也没事，是按已输入部分找对应用户，基本不可能会和别的用户有冲突。
