### ISSUE TITLE
能否优化微博图片显示

### ISSUE THREAD

**Issue by JunQu** [oxyry/qireader#52]
目前微博的图片是加载不出来的，因为微博加了防盗链的方式。
看了一下微博是通过 referrer 校验防盗链的，能否针对微博做出优化呢

比如这个订阅：

https://rsshub.app/weibo/user/1929185323

**Comment by weijarz** [comment]
似乎也不全是检测referer,我这边已经给所有图片去掉了发送referer头以绕过一些靠referer检测的防盗链。
比如这个源里的图片， 我用浏览器直接打开图片地址是打不开的（http 403），但用user agent插件切成curl就可以打开。
这样的话似乎只能在服务器上实现源图片代理才能解决这个问题了，这个功能在计划中，但还要一段时间。

**Comment by weijarz** [comment]
已经修复。
