### ISSUE TITLE
V2EX能否做到展示评论区

### ISSUE THREAD

**Issue by lf2021** [oxyry/qireader#56]
![image](https://github.com/oxyry/qireader/assets/43476344/a411619d-02c3-4fd0-8483-6008a29f92b3)
![image](https://github.com/oxyry/qireader/assets/43476344/adb89642-44fc-4d41-a606-814b6109ae7b)

如图，直接打v2ex的网站是可以展示评论区的，我不清楚能否做到这点

**Comment by weijarz** [comment]
这个做不到，因为评论是动态更新的，不可能一有新评论就去爬一下页面，只能开新页面直接打开v2ex的对应帖子。
通过按住shift点击帖子列表直接打开帖子页面。
如果是键盘操作的话在列表上按v
