### ISSUE TITLE
需要一个升级套餐的入口

### ISSUE THREAD

**Issue by JenyuShiu** [oxyry/qireader#60]
pro套餐的用户，该怎样升级我的套餐到pro+？

**Comment by weijarz** [comment]
你好，

兑换码永远不会失效。
目前还没有到期的账号只能使用同一套餐的兑换码，不同套餐升级/降级最迟最迟明天会加上。

**Comment by weijarz** [comment]
@JenyuShiu 现在应该可以了。之前没用完的会根据价格大至换算成天数加入新套餐。

**Comment by JenyuShiu** [comment]
> @JenyuShiu 现在应该可以了。之前没用完的会根据价格大至换算成天数加入新套餐。

是的，我已经成功切换了新套餐，感谢帮助。
