### ISSUE TITLE
【Bug反馈】HelloGithub 的月刊 RSS 源最近一直在更新，但被判定为无更新

### ISSUE THREAD

**Issue by takashiki** [oxyry/qireader#68]
https://hellogithub.com/rss
可能是因为这个 rss 的内容是正序排列的，所以到一定数量之后被忽略了。

**Comment by weijarz** [comment]
确实，这边只会处理反向排序的RSS。
RSS不应该正序排列，因为文章数量越来越多后，正序排列的RSS页面也会无限增大。
