### ISSUE TITLE
感谢作者大大，希望增加Kindle浏览器适配，谢谢！

### ISSUE THREAD

**Issue by thudayu** [oxyry/qireader#7]
感谢作者大大，希望增加Kindle浏览器适配，谢谢！
现在Kindle浏览器上显示不出来。

**Comment by weijarz** [comment]
@thudayu Kindle浏览器的内核还停在10年前，以qireader所用到的前端技术(solidjs)无法兼容。这边只计划兼容国产Android电子书。

**Comment by weijarz** [comment]
现在的最新固件似乎能打开了，不过我的kindle比较老所以非常慢且容易崩，不知道最新的kindle型号有没有改进。这边需要再优化下性能。
