### ISSUE TITLE
建议兼容 canonical link 规范

### ISSUE THREAD

**Issue by makediff** [oxyry/qireader#72]
你好开发者，
请问可以对文章的详细页面支持 canonical link 规范吗？
我们是五彩团队，接到用户反馈，说划线后在原始页面无法显示高亮。

比如对于qireader文章
https://www.qireader.com/subscriptions/r5oL3B4lbXxBe0Jw/entries/95pLANWwXOKqRnyP

能否在 Html meta 里添加 这个呢？
`<link rel="canonical" href="这里写原始文章地址，而不是qi reader地址"/>`

这样之后，用户在 qireader 里阅读划线后，用户在原文也能看到自己的划线了。

ps: [五彩插件](https://www.dotalk.cn/product/wucai)
期待你的回复，感谢。

**Comment by weijarz** [comment]
这里链接到的是qireader.com的文章网址？而不是原始的文章地址？

**Comment by makediff** [comment]
想要的是原文的地址。
不好意思，我上面填写错了，我修改一下。

**Comment by makediff** [comment]
你好开发者～
期望的是canonical里能写原文地址

希望能支持，期待你的回复

**Comment by weqoocu** [comment]
期待这个功能，在qireader中的划线，打开源文档也能看到对应的划线

**Comment by weijarz** [comment]
@makediff 因为这边是纯客户端渲染，象传统那样在http原始返回的html源里加这个连接不简单。
这边只能是动态的在客户端路由到这个地址时，通过javascript加在html head里，这样可不可以？

**Comment by makediff** [comment]
谢谢你的回复～
理论上是可以的。
这里有个加载逻辑，貌似需要在路由跳转前设置这个

**Comment by weijarz** [comment]
跳转前修改有点难度。这个不能路由变动后迟延一会检查这个标签吗？

**Comment by weijarz** [comment]
这个功能已经加上。

**Comment by makediff** [comment]
感谢，非常赞👍👍
后面的我们来跟进了🤝🤝

**Comment by makediff** [comment]
我们这边已经联调通过，非常感谢 @weijarz 
能将 五彩+qireader+原站点 打通了
