### ISSUE TITLE
有没有浏览器插件，可以快速订阅到qi reader

### ISSUE THREAD

**Issue by weqoocu** [oxyry/qireader#74]
目前手动复制rss到 qi reader有点累

**Comment by github-logic** [comment]
Rsshub Radar有这样的功能，但不支持Qireader,可以试试先订阅到其他阅读器上，再导出为opml文件

**Comment by weijarz** [comment]
@weqoocu 可以用楼上提到的 [RSSHub-Radar](https://github.com/DIYgod/RSSHub-Radar)
QiReader支持已经刚加到代码库里 https://github.com/DIYgod/RSSHub-Radar/pull/846 ，等下次发版时就可以了。
