### ISSUE TITLE
有一些源 Innoreader 和 Reeder 可以订阅，但 Qireader 无法订阅

### ISSUE THREAD

**Issue by starding** [oxyry/qireader#76]
举例：

RSS 地址：https://chuan.us/feed

Reeder 表现：
<img width="1245" alt="image" src="https://github.com/oxyry/qireader/assets/3321046/8404ca53-6e4d-4080-a2af-77dac9f1a8f8">

Qireader 会报错：
<img width="491" alt="image" src="https://github.com/oxyry/qireader/assets/3321046/4f945ad5-bf5c-41a5-9c86-3b10be3ac554">

看起来是因为 XML 中 title 字段是空的原因，不太确定背后的校验机制，但这个校验似乎太强了。
如果解析时取不到 title 值，又暂时不支持自定义名称的话，能否直接用域名作为后备字段？比直接无法同步体验好很多。 
<img width="1004" alt="image" src="https://github.com/oxyry/qireader/assets/3321046/10c78ff9-13ad-46db-8de4-4da090a8561d">

**Comment by weijarz** [comment]
这个确实应该允许添加空标题的源，虽然规范上要求必需。
在feedly试了下也可以，只是显示空白标题，这边后续会用域名代替。

**Comment by weijarz** [comment]
已修复。当前时间点后新出的文章可以正常收录了。
