### ISSUE TITLE
作者能提供后订阅 API吗？希望在RSShub里面快速订阅到Qi Reader

### ISSUE THREAD

**Issue by SNANA51832** [oxyry/qireader#77]

**Comment by weijarz** [comment]
你说的订阅API是具体指什么？

**Comment by github-logic** [comment]
> 你说的订阅API是具体指什么？

RssHub Radar浏览器扩展插件提供了一项功能，可以将当前网页的rss订阅直接添加到一些常用的rss阅读器内，比如Inoreader等，而不必复制rss订阅连接再进入阅读器进行添加，提问的这个人应该想要的就是这个功能

**Comment by weijarz** [comment]
https://github.com/oxyry/qireader/issues/74
已添加到 RSSHub-Radar
