### ISSUE TITLE
进入订阅界面，不知道如何返回

### ISSUE THREAD

**Issue by weqoocu** [oxyry/qireader#83]
- 快捷键a,进入添加订阅，进入这个页面后，不知道如何返回，esc不行，也没有按钮

<img width="1534" alt="image" src="https://github.com/oxyry/qireader/assets/35360006/ca10b6ed-ef78-4765-a98b-856d81ea2b0b">

- 另外快捷键可以自定义么？ a已经安排给了另外一个软件。

**Comment by sogoo** [comment]
左上角打开侧边栏按钮

**Comment by weqoocu** [comment]
> 左上角打开侧边栏按钮

还真不知道有这个按钮，最好支持esc

**Comment by weijarz** [comment]
这是一个单独的浏览器页面，可以用浏览器的后退快捷键返回，比如 alt + 左方向键
