### ISSUE TITLE
Version: 16.10.6，网页版，鼠标点击，无选中项，选不了条目

### ISSUE THREAD

**Issue by mhm300** [oxyry/qireader#88]
选不了条目

**Comment by wenhairu** [comment]
![240317_213454](https://github.com/oxyry/qireader/assets/19679373/4b089a8a-48d3-4aa4-9f27-375ba63dab7e)

确实坏掉了，打不开内容页，梦回十年前~

**Comment by weijarz** [comment]
谢谢反馈，已修复。
