### ISSUE TITLE
添加订阅源取消订阅选项

### ISSUE THREAD

**Issue by JamYiz** [oxyry/qireader#90]
在全部订阅源处没有办法取消订阅，很不方便。
![图片](https://github.com/oxyry/qireader/assets/44351690/40806301-e44e-4462-872e-fd1ab3d42287)

**Comment by weijarz** [comment]
的确应该在这个边栏里可以直接取消订阅。

目前的话可以在文章列表点击文章标题上边的订阅名进入单独的订阅文章列表，然后点文章列表上面的“...”下拉菜单，选择取消订阅。

**Comment by weijarz** [comment]
已经修复。
