### ISSUE TITLE
Partial to full text conversion

### ISSUE THREAD

**Issue by kukacz** [oxyry/qireader#95]
Hi, I've switched from Kindle4ss service, and I am missing the "partial-text to full-text" feature here. Ie. replacing the short article preview with full article text in the feeds that only provide the shortened versions. Do you plan to add that feature in qireader too?

Thank you.

Lukas

**Comment by weijarz** [comment]
Qireader automatically determines whether the source is full text, It is automatically converted to full text when sending EPUB.. 
If you need to force full-text conversion when sending EPUB or read online, first select this subscription source, then tap the "..." menu above the article list, select "Feed Properties", and in the "Default View" settings select "WebPage Text".

**Comment by kukacz** [comment]
@weijarz thanks for the reply! I've been using the default "Use global setting" which refers to "Auto-load webpage text" at the feed level. Is it supposed to make any difference when I override the default to "Webpage text" at the feed level? It sounds to me the same.

![image](https://github.com/oxyry/qireader/assets/17200879/33ed77b7-fdbf-4e2a-b813-003374afa3a9)

My experience is that in most cases the full page text is loaded when having these defaults . But there are some feeds or sometimes even just individual articles, where it does not. One example of such feed is https://feeds.arstechnica.com/arstechnica/technology-lab. Having it set to "Use global setting" while having the global setting at "Auto-load webpage text" renders as partial feed text only. But when I set the feed-level property to "Webpage text", then it loads the full text reliably. There are other pages though, as https://devops.com/feed, where the default setting always correctly loads full page even though the site only provides summary text in their RSS feed.

I could probably resolve my situation by manually overriding configuration of all problematic feeds. I would rather rely on the global setting though, which suggests that it should ensure the full page loading. Or am I reading it wrong perhaps?

**Comment by weijarz** [comment]
@kukacz "Auto-load webpage text" means using of an algorithm to determine whether the feed is a fulltext feed or not, and if it is not a fulltext feed then the text is loaded from the corresponding web page. Most of the time this algorithm will determine this correctly. Set "Webpage text" on a feed means always load text from the web page, even if the feed is already a full text feed.
