### ISSUE TITLE
稍后再读数量始终显示为0

### ISSUE THREAD

**Issue by JerryYang-30** [oxyry/qireader#98]
稍后再读文章数量一直显示为0，但里面明明存了文章

![Screenshot_20240508_133745_mark via](https://github.com/oxyry/qireader/assets/102589310/30a51176-6e00-4cc6-971a-964c25fca060)

![Screenshot_20240508_133727_mark via](https://github.com/oxyry/qireader/assets/102589310/1c84ddf9-b250-4c99-8e05-437b8a35c0e7)

**Comment by weijarz** [comment]
这是个显示bug😄设计上稍后阅读列表和标签文章列表在边栏和标题栏都应该不会显示统计数字,今天的更新已经去掉了这个数字0。
