### ISSUE TITLE
暂停自动刷新

### ISSUE THREAD

**Issue by xjr7670** [oxyry/qireader#99]
有切换自动刷新的功能吗？
目前都是自动刷新的，我希望手动更新。
自动更新的话有时候有些想读的未读文章还没看就被埋到底下了。
目前在界面上没有看到停止自动更新的功能。
我用的是 qireader.com

**Comment by weijarz** [comment]
别的rss reader打开订阅源时似乎也都会自动更新文章列表。
这边计划实现的文章从旧到新排序功能应该可以解决老文章被刷在下面的问题。

**Comment by xjr7670** [comment]
打开（添加）订阅源时自动更新是合理的。我是意思是在阅读的时候，左边的列表也会自动更新，我希望是可以允许用户自行切换为手动执行刷新。
文章从旧到新排序感觉会有另外一个问题，旧的文章必然比新的更多，从旧到新排那岂不是更加会把当前较新的文章埋在底下

**Comment by weijarz** [comment]
这个是可以考虑加个按钮手动加载新文章。

目前的逻辑是，滚动条在顶部300像素内会自动加载新文章，不在顶部不会加载（否则可能会造成正在看的文章列表突然下移，虽然浏览器一般会正确处理这种下移）。如果从下面滚动到顶部也会自动加载。

**Comment by xjr7670** [comment]
那我明白了。就是目前可以通过滚动条来控制。
谢谢
